const upcomingMovies = {
  results: [
    {
      adult: false,
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      genre_ids: [28, 80, 53],
      id: 1249289,
      original_language: "en",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      popularity: 1766.016,
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      release_date: "2025-01-16",
      title: "Alarum",
      video: false,
      vote_average: 5.8,
      vote_count: 141,
    },
    {
      adult: false,
      backdrop_path: "/u7AZ5CdT2af8buRjmYCPXNyJssd.jpg",
      genre_ids: [28, 35],
      id: 1160956,
      original_language: "zh",
      original_title: "熊猫计划",
      overview:
        "International action star Jackie Chan is invited to the adoption ceremony of a rare baby panda, but after an international crime syndicate attempts to kidnap the bear, Jackie has to save the bear using his stunt work skills.",
      popularity: 1683.17,
      poster_path: "/xVS9XiO9upp2SnWx6KpBYb79hLR.jpg",
      release_date: "2024-10-01",
      title: "Panda Plan",
      video: false,
      vote_average: 6.211,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/eHu1ZxFPmqyhnait9VdsOQBEFOk.jpg",
      genre_ids: [27, 53],
      id: 710295,
      original_language: "en",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      popularity: 1521.794,
      poster_path: "/jTPBMPTgk9zOUGSkWcoOGbX8cTi.jpg",
      release_date: "2025-01-15",
      title: "Wolf Man",
      video: false,
      vote_average: 6.4,
      vote_count: 270,
    },
    {
      adult: false,
      backdrop_path: "/h7r6LZ32dgLwtwSW3CxoWIYD9pr.jpg",
      genre_ids: [27, 14],
      id: 426063,
      original_language: "en",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      popularity: 1189.734,
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      release_date: "2024-12-25",
      title: "Nosferatu",
      video: false,
      vote_average: 6.663,
      vote_count: 1988,
    },
    {
      adult: false,
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      genre_ids: [16, 14, 12],
      id: 823219,
      original_language: "lv",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      popularity: 585.271,
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      release_date: "2024-08-29",
      title: "Flow",
      video: false,
      vote_average: 8.3,
      vote_count: 1087,
    },
    {
      adult: false,
      backdrop_path: "/i3CAo9UMGsvlU9k3Svd63rRDeZx.jpg",
      genre_ids: [16, 18, 35],
      id: 1064486,
      original_language: "en",
      original_title: "Memoir of a Snail",
      overview:
        "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
      popularity: 570.766,
      poster_path: "/57AgZv1ITeBLShiNdchZ5153evs.jpg",
      release_date: "2024-10-17",
      title: "Memoir of a Snail",
      video: false,
      vote_average: 7.647,
      vote_count: 139,
    },
    {
      adult: false,
      backdrop_path: "/kEYWal656zP5Q2Tohm91aw6orlT.jpg",
      genre_ids: [18, 35, 10749],
      id: 1064213,
      original_language: "en",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      popularity: 569.745,
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      release_date: "2024-10-14",
      title: "Anora",
      video: false,
      vote_average: 7.1,
      vote_count: 977,
    },
    {
      adult: false,
      backdrop_path: "/7bIWKyWdT04HTY3PqLETT8CH7jo.jpg",
      genre_ids: [28, 80, 53],
      id: 974453,
      original_language: "en",
      original_title: "Absolution",
      overview:
        "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      popularity: 558.898,
      poster_path: "/gt70JOD9xsPlpJnuBJAWdOT4yRg.jpg",
      release_date: "2024-10-31",
      title: "Absolution",
      video: false,
      vote_average: 5.8,
      vote_count: 297,
    },
    {
      adult: false,
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      genre_ids: [27, 53],
      id: 1138194,
      original_language: "en",
      original_title: "Heretic",
      overview:
        "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      popularity: 426.376,
      poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      release_date: "2024-10-31",
      title: "Heretic",
      video: false,
      vote_average: 7.174,
      vote_count: 1061,
    },
    {
      adult: false,
      backdrop_path: "/mKIxSo3p1QKlsdegcOwapcbiV74.jpg",
      genre_ids: [28, 80, 53],
      id: 604685,
      original_language: "en",
      original_title: "Den of Thieves 2: Pantera",
      overview:
        "Big Nick is back on the hunt in Europe and closing in on Donnie, who is embroiled in the treacherous and unpredictable world of diamond thieves and the infamous Panther mafia, as they plot a massive heist of the world's largest diamond exchange.",
      popularity: 422.772,
      poster_path: "/zLHq7fQA3xpck5UIHcRYgip5pQD.jpg",
      release_date: "2025-01-08",
      title: "Den of Thieves 2: Pantera",
      video: false,
      vote_average: 6.717,
      vote_count: 203,
    },
    {
      adult: false,
      backdrop_path: "/8eifdha9GQeZAkexgtD45546XKx.jpg",
      genre_ids: [878, 28, 53],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      popularity: 389.771,
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      release_date: "2025-02-12",
      title: "Captain America: Brave New World",
      video: false,
      vote_average: 8.3,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 352.997,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.451,
      vote_count: 36428,
    },
    {
      adult: false,
      backdrop_path: "/9s9o9RT9Yj6nDuRJjnJm78WFoFl.jpg",
      genre_ids: [28, 27, 53, 878],
      id: 1051896,
      original_language: "en",
      original_title: "Arcadian",
      overview:
        "In the near future, on a decimated Earth, Paul and his twin sons face terror at night when ferocious creatures awaken. When Paul is nearly killed, the boys come up with a plan for survival, using everything their father taught them to keep him alive.",
      popularity: 344.853,
      poster_path: "/h4T8Xeydkw53h9uIbulYsss25UF.jpg",
      release_date: "2024-04-12",
      title: "Arcadian",
      video: false,
      vote_average: 6.132,
      vote_count: 593,
    },
    {
      adult: false,
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      genre_ids: [878, 27, 35, 53],
      id: 1084199,
      original_language: "en",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      popularity: 321.276,
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      release_date: "2025-01-22",
      title: "Companion",
      video: false,
      vote_average: 7.072,
      vote_count: 207,
    },
    {
      adult: false,
      backdrop_path: "/7uGoDVlmB7JT2JrQ6fvNPoQeAo0.jpg",
      genre_ids: [16, 14, 12],
      id: 980477,
      original_language: "zh",
      original_title: "哪吒之魔童闹海",
      overview:
        "After the tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies would soon be completely destroyed.Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical bodies. But in the process of reshaping their physical bodies, they encountered numerous difficulties. Where will the fate of Ne Zha and Ao Bing go?",
      popularity: 313.09,
      poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
      release_date: "2025-01-29",
      title: "Ne Zha 2",
      video: false,
      vote_average: 7.8,
      vote_count: 42,
    },
    {
      adult: false,
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      genre_ids: [18, 9648, 53],
      id: 974576,
      original_language: "en",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      popularity: 288.136,
      poster_path: "/vYEyxF1UT779RiEalpMjUT6kfdf.jpg",
      release_date: "2024-10-25",
      title: "Conclave",
      video: false,
      vote_average: 7.078,
      vote_count: 1142,
    },
    {
      adult: false,
      backdrop_path: "/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg",
      genre_ids: [18, 53],
      id: 974950,
      original_language: "fr",
      original_title: "Emilia Pérez",
      overview:
        "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.",
      popularity: 273.512,
      poster_path: "/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg",
      release_date: "2024-08-21",
      title: "Emilia Pérez",
      video: false,
      vote_average: 7.114,
      vote_count: 1183,
    },
    {
      adult: false,
      backdrop_path: "/1LSMstNHwJnJD7tpnb8gZcgGNQR.jpg",
      genre_ids: [27, 53],
      id: 1164355,
      original_language: "id",
      original_title: "Lembayung",
      overview:
        "Arum and Pica, who wanted to complete their internship at Lembayung hospital, had to face mysterious terror from a woman satan who was suspected of hanged herself in the bathroom. The situation became even more tense after they asked others for help to the point where they threatened their own lives and those closest to them.",
      popularity: 253.635,
      poster_path: "/5x9LrW0yvtt6S3XovIQHgXfYvLL.jpg",
      release_date: "2024-09-19",
      title: "Lembayung",
      video: false,
      vote_average: 7.8,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/hmZnqijPaaACjenDkrbWcCmcADI.jpg",
      genre_ids: [18],
      id: 549509,
      original_language: "en",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Toth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      popularity: 242.539,
      poster_path: "/lKkWcdqDEPEMVmLxRJGwJxJp5XB.jpg",
      release_date: "2024-12-20",
      title: "The Brutalist",
      video: false,
      vote_average: 6.6,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
      genre_ids: [53, 28, 80],
      id: 1126166,
      original_language: "en",
      original_title: "Flight Risk",
      overview:
        "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
      popularity: 237.026,
      poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
      release_date: "2025-01-22",
      title: "Flight Risk",
      video: false,
      vote_average: 6.1,
      vote_count: 67,
    },
  ],
};

module.exports = { upcomingMovies };
